[project]
name = "sigui_ofratemap"
version = "0.1.0"
description = "Custom view plugin for SpikeInterfaceGUI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pynapple>=0.10.1",
]

[build-system]
requires = ["setuptools>=62.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["sigui_ofratemap"]

# Register your custom views
[project.entry-points."spikeinterface_gui.views"]
ratemapview = "sigui_ofratemap.ratemap:RateMapView"
